export const allOperationalPermissions = [
  'orders:view',
  'orders:view_branch',
  'orders:create',
  'orders:update',
  'orders:submit',
  'orders:approve',
  'orders:reject',
  'orders:return_for_edit',
  'fulfillment_coordinator',
  'fulfillment:split',
  'production_operator',
  'packing:pack',
  'delivery:batch_create',
  'delivery:assign_driver',
  'delivery_driver',
  'payment.collect_branch',
  'payment.collect_delivery',
  'payment.view_own',
  'payment.view_all',
  'cashbox.view_own',
  'cashbox.view_all',
  'cashbox.submit',
  'cashbox.review',
  'cashbox.approve',
  'cashbox.return',
  'cashbox.close_day',
  'accounting.view_financials',
  'accounting.review_sales_order',
  'accounting.submit_sales_order',
  'accounting.review_invoice',
  'accounting.submit_invoice',
  'accounting.review_payment',
  'accounting.submit_payment',
  'accounting.reconcile_payments',
  'accounting.close_financial_day',
  'erpnext.view_sync_logs',
  'erpnext.retry_sync',
  'erpnext-sync:manage',
  'master-data:manage',
  'notifications:view',
  'notifications:read',
  'reports.view_operations',
  'reports.view_financials',
  'reports.view_erpnext',
  'admin.users.view',
  'admin.users.manage',
  'admin.roles.view',
  'admin.roles.manage',
  'admin.settings.view',
  'admin.settings.manage',
  'admin.master_data.view',
  'admin.master_data.manage',
  'admin.erpnext.view',
  'admin.erpnext.retry',
  'admin.erpnext.products_sync',
  'admin.reports.view',
] as const;

export const rolePermissionMap = {
  BRANCH_OPERATOR: [
    'orders:view',
    'orders:view_branch',
    'orders:create',
    'orders:update',
    'orders:submit',
    'payment.collect_branch',
    'payment.view_own',
    'cashbox.view_own',
    'cashbox.submit',
    'notifications:view',
    'notifications:read',
  ],
  BRANCH_SUPERVISOR: [
    'orders:view',
    'orders:view_branch',
    'orders:approve',
    'orders:reject',
    'orders:return_for_edit',
    'reports.view_operations',
    'notifications:view',
    'notifications:read',
  ],
  FULFILLMENT_COORDINATOR: [
    'orders:view',
    'fulfillment_coordinator',
    'fulfillment:split',
    'packing:pack',
    'reports.view_operations',
    'notifications:view',
    'notifications:read',
  ],
  PRODUCTION_OPERATOR: [
    'production_operator',
    'notifications:view',
    'notifications:read',
  ],
  DRIVER: [
    'delivery_driver',
    'payment.collect_delivery',
    'payment.view_own',
    'notifications:view',
    'notifications:read',
  ],
  CASHIER: [
    'cashbox.view_own',
    'cashbox.view_all',
    'cashbox.review',
    'cashbox.approve',
    'cashbox.return',
    'cashbox.close_day',
    'payment.view_all',
    'reports.view_financials',
    'notifications:view',
    'notifications:read',
  ],
  ACCOUNTANT: [
    'accounting.view_financials',
    'accounting.review_sales_order',
    'accounting.submit_sales_order',
    'accounting.review_invoice',
    'accounting.submit_invoice',
    'accounting.review_payment',
    'accounting.submit_payment',
    'accounting.reconcile_payments',
    'accounting.close_financial_day',
    'erpnext.view_sync_logs',
    'erpnext.retry_sync',
    'reports.view_financials',
    'reports.view_erpnext',
    'notifications:view',
    'notifications:read',
  ],
  PLATFORM_ADMIN: allOperationalPermissions,
} as const;

export type AuthRoleCode = keyof typeof rolePermissionMap;
